#################### Macros #####################

PROJ = FontEditor

OBJECTS = 
INCLUDE = -I../../SDL-1.2.14/include/SDL -Iinclude

EXTERNAL_BIN = ../../SDL-1.2.14/bin
TARGETNAME = FontEditor
TARGET_OBJECTS = Main

TESTERNAME = Test
TESTER_OBJECTS = TesterMain

# CC macros
COMMON_CFLAGS = -static-libgcc
CFLAGS = -O0 -g -mwindows
CDEFINES =

# CPP macros (additional to C macros)
COMMON_CPPFLAGS = -static-libstdc++
CPPFLAGS = 
CPPDEFINES =

# Universal macros
LIBS = -L../../SDL-1.2.14/lib -lmingw32 -lSDLmain -lSDL -lpthread.dll
SOURCE = src
TARGET = .

include cpp_exec.mk